### PR TITLE
Convert from Netflix Zuul to Spring Cloud Gateway

### PR DESCRIPTION
**Pull request by simpleauthority**
Also brings us to the latest Spring Boot.

### CODE REVIEW

**Comment by simpleauthority** [comment]
gateway now starts and routes register, moving on to initial testing

**Comment by simpleauthority** [comment]
tested every api route except user stuff, recompiling frontend to point @ test env to test auth stuff. if all good, then ready for review shortly.

**Comment by simpleauthority** [comment]
and God said let there be no more request blockage and there was no more request blockage.

**Comment by simpleauthority** [comment]
doing some final testing

**Comment by simpleauthority** [comment]
Everything seems to work. Tested every route and the website.

**Review by darbyjack — APPROVED** [review]

**Pull request merged**
